### ISSUE TITLE
Fix for 21 - LibNetworkStack Update

### ISSUE THREAD

**Issue by SylisMC** [Juuxel/VanillaParts#23]
I'm sure youre quite busy, but I noticed Alex released a fixed version but he didn't upload it to his official page for some reason, I just wanted to make sure this didn't get missed in the comments, thanks for the awesome work!

"I've released a fixed version of LibNetworkStack: [0.4.3](https://alexiil.uk/maven/alexiil/mc/lib/libnetworkstack-base/0.4.3/libnetworkstack-base-0.4.3.jar)."

_Originally posted by @AlexIIL in https://github.com/Juuxel/VanillaParts/issues/21#issuecomment-747139748_

**Comment by AlexIIL** [comment]
In the the cotton discord, from Juuxel: `@AlexIIL: Could you make a new release of LMP so I don't have to jij LNS twice? (both in LMP and directly in my mod)`

So, this is waiting on me. (I haven't pushed an LMP update quite yet because I planned to add breaking/hit particles&sound support for parts).

Although (from me): `If you need something quicker than I push though you can always jar-in-jar LMP base rather than all, as that doesn't contain any of its deps. (So you'd need to include LBA core too)`.

**Comment by SylisMC** [comment]
> In the the cotton discord, from Juuxel: `@AlexIIL: Could you make a new release of LMP so I don't have to jij LNS twice? (both in LMP and directly in my mod)`
> 
> So, this is waiting on me. (I haven't pushed an LMP update quite yet because I planned to add breaking/hit particles&sound support for parts).
> 
> Although (from me): `If you need something quicker than I push though you can always jar-in-jar LMP base rather than all, as that doesn't contain any of its deps. (So you'd need to include LBA core too)`.

Thanks for the response and for being professional, i just wanted to make sure your comment didn't get missed in issue 21
(i actually tried to update the core jar manually for personal use but it failed to recognize the new jar, something needs to be updated within vanillaparts aswell so for now ill just have to be patient)

As always, thanks for all the hard work you do for the community, we appreciate it

**Comment by AlexIIL** [comment]
Okay, I've released LibMultiPart [0.4.6](https://alexiil.uk/maven/alexiil/mc/lib/libmultipart-all/0.4.6/libmultipart-all-0.4.6.jar), which both fixes this and adds hit particles and sounds.
